### ISSUE TITLE
No test result file when outputing an escape sequence 

### ISSUE THREAD

**Issue by jairbubbles** [spekt/junit.testlogger#62] opened 2023-02-01 15:01 UTC
While investigating why my test result was not created for my projects, I realized that it was due to some tests that were outputting escape sequences.

To reproduce the issue, you can just use this test:

```csharp
[Test]
public void Test()
{
    Console.WriteLine("test\0");
}
```

**Comment by Siphonophora** [comment] 2023-02-05 16:33
Duplicate of #59

**Closed as not planned by Siphonophora** 2023-02-05 16:33 UTC
