### ISSUE TITLE
Junit result xml files are not being generated for versions > 3.0.98

### ISSUE THREAD

**Issue by kabilanmani93** [spekt/junit.testlogger#64] opened 2023-04-03 11:26 UTC
Dotnet Project

Docker base image used : mcr.microsoft.com/dotnet/sdk:6.0.405-alpine3.17

**Command used:** 
`dotnet test --test-adapter-path:. --collect "Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=tests/TestResults /p:UseSourceLink=true --logger:"junit;LogFileName=junit-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --logger "trx;LogFileName=testresults.trx;Parser=Legacy" --results-directory valid/ `

**Issue**: 
Junit result xml files are not being generated for versions > 3.0.98

But if either we **REMOVE** the flag --collect "Code Coverage" then the junit xml's are generated
or
instead pass --collect "XPlat Code Coverage" then the junit xml's are generated

having --collect " code coverage" the junt result xmls are not generated

**Comment by Siphonophora** [comment] 2023-04-15 18:27
@kabilanmani93 So, files were generated on [v3.0.87](https://github.com/spekt/junit.testlogger/releases/tag/v3.0.87)?

`--collect "Code Coverage"` doesn't alter the xml report that we generate, right? Maybe it adds standard output that gets logged in our report?

It isn't obvious to me how these could be interfering with each other, so I think we may need an example to move this forward. Unless

**Comment by codito** [comment] 2023-07-06 12:30
@kabilanmani93 I had a chance to debug a similar issue recently. It was with coverlet collector. The problem is Coverlet also instruments the Spekt.* dlls which changes some of the event handlers.

Is it possible to try excluding Spekt.* and JUnitXml* dlls from code coverage instrumentation?

If this doesn't work, could you share the `log.*` files generated with `dotnet test --diag:log.txt` command?

**Comment by chrisandchris** [comment] 2023-09-01 16:09
I can confirm this behaviour:

* 🚫 with XPlat Code Coverage (coverlet collector 6.0.0) and Junit Logger 3.0.110, no xml files are generated
* 🆗 with XPlat Code Coverage (coverlet collector 6.0.0) and Junit Logger 3.0.98, the xml files are generated
* 🚫 with MS Code Coverage 17.7.2 and Junit Logger 3.0.110, no xml files are generated
* 🆗 with MS Code Coverage 17.7.2 and Junit Logger 3.0.98, the xml files are generated

We currently just made sure that 3.0.98 is installed and then we have the xml log files.

**Comment by codito** [comment] 2023-09-01 17:42
Thanks @chrisandchris for confirmation. Is it possible to share the log.* files generated with `dotnet test --diag:log.txt` command?

**Comment by robrich** [comment] 2023-12-30 16:55
Could it be related to this?: https://github.com/spekt/xunit.testlogger/issues/51#issuecomment-1872528782

**Comment by chrisandchris** [comment] 2024-01-19 09:55
> Thanks @chrisandchris for confirmation. Is it possible to share the log.* files generated with `dotnet test --diag:log.txt` command?

Sorry for the very late response. We stayed on 3.0.98 and then somehow we forgot to generate the logs.

Following command:

```
dotnet test --no-restore \
    --no-build \
    --test-adapter-path:. \
    --diag:log.txt \
    --collect:"Code Coverage;Format=cobertura" \
    --logger "junit;LogFilePath=./junit-{assembly}.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
```

With JunitXml.TestLogger 3.0.134, i have the following log.txt: [log.txt](https://github.com/spekt/junit.testlogger/files/13987308/log.txt)

However, I could not reliably reproduce the issue with the missing junit-xml. It worked on my machine, but our Gitlab Runner did not produce it. I'll investigate further (hopefully a bit faster...).

**Comment by timo-reymann** [comment] 2024-01-29 15:57
@chrisandchris I find myself in the same situation, just with the Xunit XML logger. Also works locally, but not on the GitLab runners.

For some reason after a few builds it magically starts to work. In CI obviously the build only runs once, and all files are thrown aways as it runs in a container.

Maybe you have the same situation? 

I can reproduce it by `dotnet clean`, run a build and than run `dotnet test --no-build` locally.

**Comment by codito** [comment] 2024-02-09 14:00
We found that code coverage _instrumentation_ is messing up the test result reporting callbacks. Please check if this workaround helps: https://github.com/spekt/junit.testlogger/issues/72#issuecomment-1935974284. If anyone tries this, please report back if the workaround helped.

Tracking a fix in above issue.

**Comment by codito** [comment] 2024-02-10 01:26
Fix released with https://www.nuget.org/packages/JunitXml.TestLogger/3.1.12.

**Closed as completed by codito** 2024-02-10 01:26 UTC
